name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Install dependencies
        run: dotnet restore ServerPickerX.slnx
      - name: Build
        run: dotnet build ServerPickerX.slnx --no-restore
      - name: Test (XUnit)
        run: dotnet test ServerPickerX.Tests.slnx